name = "CircleFit"
uuid = "a2741ea9-3318-4d4b-8b99-ae5c58b57db7"
authors = ["Michael Pusterhofer <pusterhofer@student.tugraz.at>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
